### ISSUE TITLE
X-Frame-Options

### ISSUE THREAD

**Issue by thewilloftheshadow** [ploogins/powercord-openlinks#2]
If a website has the `X-Frame-Options` header set to "DENY", then the popout should show an error or message, instead of opening to a blank screen

**Comment by AAGaming00** [comment]
This is unfortunately a Powercord issue(I think), as they removed the part that strips that header, and I don't believe there's a way for me to detect that (without making a separate request)

**Comment by ghost** [comment]
If possible, we could enable "webview" tag in Electron and use `<webview>` instead of `<iframe>`.

**Comment by AAGaming00** [comment]
yes, but idk how to do so without remote ( can technically abuse remote debugger but e h )
